### PR TITLE
Accordion results

### PR DESCRIPTION
**Pull request by smashwilson**
This adds a banner to each result element containing the execution count of each, and responds to clicks on the banner by collapsing and expanding that result.

accordion

- [x] Convert the `sidecar-error` component to also support collapsing and expanding.
 - [x] Refactor `sidecar-error` to just be a `sidecar-result` with special styling. They're basically the same thing.
- [x] Implement a close button on each result element to trash it.
- [x] Provide titles for stacktrace results.
- [x] Use error styling for stderr output.

### CODE REVIEW

**Comment by rgbkrk** [comment]
OMG, yes!

By the way, you can upgrade `jupyter_console` (will fix that warning banner).

**Comment by smashwilson** [comment]
> OMG, yes!

:grin:

> By the way, you can upgrade `jupyter_console` (will fix that warning banner).

How so, just by doing a `git pull` in the jupyter_console repo?

**Comment by smashwilson** [comment]
I was originally thinking about making them auto-collapse when a new execution result arrives, but now I'm not so sure. What do you think?

I'll make a checklist for remaining work :point_up:

**Comment by rgbkrk** [comment]
I wouldn't make them auto-collapse. When working on a more data oriented project, I might have multiple plots or outputs I want to show in tandem. While I could go back and open them up, what happens when new results come in? Do you keep the original state?

**Comment by rgbkrk** [comment]
> How so, just by doing a git pull in the jupyter_console repo?

You did a `pip install -e` of `jupyter_console` right? You should then be able to do a `git pull`.

**Comment by rgbkrk** [comment]
I feel bad that my last few PRs have made this have merge conflicts :exclamation:

**Comment by smashwilson** [comment]
> I feel bad that my last few PRs have made this have merge conflicts :exclamation:

Well gee, if only I had some tool to make resolving merge conflicts more easily :wink: Resolved and pushed.

I still have a few things to iron out. I'll update the checklist accordingly.

**Comment by smashwilson** [comment]
There we go:

screen shot 2015-06-30 at 10 05 42 am

I think this is ready to go, then :smile: We can make the close buttons prettier once FontAwesome gets merged in.

**Comment by rgbkrk** [comment]
Ok, this is pretty nice actually. I especially like the shadow on the inputs.

For some reason, clicking to collapse isn't working. Close is though!

**Comment by smashwilson** [comment]
> For some reason, clicking to collapse isn't working.

Oh, weird, now it isn't for me, either. I'll have a look.

**Pull request merged**
