### PR TITLE
Update electron version.

### PR DESCRIPTION
**Pull request by rgbkrk**
Alright @blink1073, let's give this a try.

Now that node zmq has updated nan, I tore out the npm shrinkwrap and did some other updates.

To get this going I made a fresh download and ran through these steps:

```
$ git clone https://github.com/rgbkrk/jupyter-sidecar
$ cd jupyter-sidecar
$ git checkout update_electron
$ npm install
$ npm install -g electron-prebuilt
$ cd node_modules/zmq
$ node-gyp rebuild --target=0.28.1 --arch=x64 --dist-url=https://atom.io/download/atom-shell
$ cd ../..
$ electron . ~/Library/Jupyter/runtime/kernel-39794.json
```

We'll want to pin electron-prebuilt in the future. Take this for a spin!

### CODE REVIEW

**Comment by rgbkrk** [comment]
Heyo, looks like `npm install --dev` works again with the ripout of grunt.

**Comment by rgbkrk** [comment]
`./node_modules/.bin/electron-rebuild` seems to be working too.

**Comment by blink1073** [comment]
Installing now

**Comment by rgbkrk** [comment]
> Installing now.

*Fingers crossed*

**Comment by blink1073** [comment]
She launches!  Thanks Kyle, well done!

**Comment by rgbkrk** [comment]
Ok, seems like `./node_modules/.bin/electron . ~/Library/Jupyter/runtime/kernel-39794.json` is useful for pinning but not the rebuild. Stuck with the node-gyp way for the moment.

**Comment by blink1073** [comment]
Out of curiosity, what is holding back support for `matplotlib inline`?

**Comment by rgbkrk** [comment]
> launches!

Wahoo! At the very least we should be able to make builds from this, sparing users from this dev setup.

**Comment by rgbkrk** [comment]
> what is holding back support for matplotlib inline

Uhhhh, it should work... I usually have to run `%matplotlib inline` in my running console *after* I've connected to sidecar.

**Comment by blink1073** [comment]
Oh, because it doesn't work in your screencast.  :smile:

**Comment by rgbkrk** [comment]
screenshot 2015-06-16 10 50 18

**Comment by rgbkrk** [comment]
> Oh, because it doesn't work in your screencast.  :smile:

Ha, my bad. I thought it wasn't working at that time when it was just how matplotlib interacts with the kernel, not sending the richer mimetypes by default.

**Comment by rgbkrk** [comment]
On that note, if you make a sweet screencast I'd happily accept it in a PR.

**Comment by blink1073** [comment]
I will if I can get my screencast software to work (waiting on IT), thanks again!

**Comment by rgbkrk** [comment]
Are you able to use [LICEcap](http://www.cockos.com/licecap/)?

**Comment by blink1073** [comment]
It looks like I can, a PR will be coming your way!

**Comment by rgbkrk** [comment]
Awesome, I'll merge this as is and be excited about the PR. Feel free to use GitHub's image service to store the animated gif. :wink:

**Pull request merged**
